import type {
  BicyclingSegmentResult,
  GeocodeCandidate,
  MapProvider
} from '../map-provider/map-provider.port';
import {
  safeParseRouteArtifact,
  type RouteArtifact
} from '../shared/validation/route-artifact.schema';

export interface OrderedRouteSegment {
  from: GeocodeCandidate;
  to: GeocodeCandidate;
  distanceMeters: number;
  durationSeconds: number;
  polyline: BicyclingSegmentResult['polyline'];
}

interface OrderedRoutePayload {
  segments: OrderedRouteSegment[];
  totalDistanceMeters: number;
  totalDurationSeconds: number;
}

const validateRouteArtifact = (payload: OrderedRoutePayload): OrderedRoutePayload => {
  const parsed = safeParseRouteArtifact(payload);
  if (!parsed.success) {
    const issues = parsed.error.issues.map((issue) => issue.path.join('.')).join(', ');
    throw new Error(`Invalid route artifact generated by segment routing: ${issues}`);
  }

  return payload;
};

export const summarizeRouteSegments = (segments: OrderedRouteSegment[]): OrderedRoutePayload => {
  const totals = segments.reduce(
    (acc, segment) => ({
      totalDistanceMeters: acc.totalDistanceMeters + segment.distanceMeters,
      totalDurationSeconds: acc.totalDurationSeconds + segment.durationSeconds
    }),
    {
      totalDistanceMeters: 0,
      totalDurationSeconds: 0
    }
  );

  return validateRouteArtifact({
    segments,
    totalDistanceMeters: totals.totalDistanceMeters,
    totalDurationSeconds: totals.totalDurationSeconds
  });
};

export const buildOrderedSegments = async (
  points: GeocodeCandidate[],
  provider: Pick<MapProvider, 'routeBicyclingSegment'>
): Promise<OrderedRoutePayload> => {
  if (points.length < 2) {
    throw new Error('At least two accepted points are required to build route segments');
  }

  const segments: OrderedRouteSegment[] = [];

  for (let index = 0; index < points.length - 1; index += 1) {
    const from = points[index];
    const to = points[index + 1];
    const route = await provider.routeBicyclingSegment({
      from: {
        lng: from.lng,
        lat: from.lat
      },
      to: {
        lng: to.lng,
        lat: to.lat
      }
    });

    segments.push({
      from,
      to,
      distanceMeters: route.distanceMeters,
      durationSeconds: route.durationSeconds,
      polyline: route.polyline
    });
  }

  return summarizeRouteSegments(segments);
};

export type RouteArtifactSummary = RouteArtifact;
